torrents:
    source: http://kickass.to
    categories: # Available options: tv, movies, music, games, applications, anime, books, lossless
        - tv
        - movies
    keywords:
        - big
        - person of interest
        - flash
        - arrow

    pages: 3


email:
    to: Masnun <masnun@gmail.com>
    subject: New Torrents Available
    from: Torrent Bot <noreply@tardis.dev>
    template: template.html
    smtp:
        host: localhost
        port: 25
        username:
        password:


mongo:
    host: localhost
    port: 27017
    database: kat2mail
    collection: torrents

